#!/bin/sh

set -e

SDK_DIR="$HOME/android/android-sdk-linux"
NDK_DIR="$HOME/android/android-ndk-r10e"

generate_local_properties() {
	: > local.properties
	echo "sdk.dir=${SDK_DIR}" >> local.properties
	echo "ndk.dir=${NDK_DIR}" >> local.properties
}

build() {
	./gradlew build
}

install() {
	adb uninstall com.example.Hologram
	adb install build/outputs/apk/android-fat-debug.apk
}

run() {
	adb shell am start com.example.Hologram/android.app.NativeActivity
}

generate_local_properties
build
install
#run
