Document: vulkan-samples
Title: Debian vulkan-samples Manual
Author: <insert document author here>
Abstract: This manual describes what vulkan-samples is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vulkan-samples/vulkan-samples.sgml.gz

Format: postscript
Files: /usr/share/doc/vulkan-samples/vulkan-samples.ps.gz

Format: text
Files: /usr/share/doc/vulkan-samples/vulkan-samples.text.gz

Format: HTML
Index: /usr/share/doc/vulkan-samples/html/index.html
Files: /usr/share/doc/vulkan-samples/html/*.html
